# vim: et ts=4 sw=4

a = 'b'
c = ['a', '', 'what',]

d = {hehe = ['dingle'],}

[file-groups]
common = [
    'michael.c',
    'tomlinson.c',
]

[file-groups.binary]
groups = ['common']
files = ['main.c']

[file-groups.library]
groups = ['common']
files = ['lib.c']

[targets]
mt = ['binary']

[targets.libmt]
groups = ['library']
files = ['bobby-hill.c']
