# vim: et ts=4 sw=4
[project]
name = "libtomato"
version = "1"

[[sources]]
name = "tomatoes"
files = [
    "beefmaster.c",
    "san_marzano.c",
]

[[sources]]
name = "grow"
files = [
    "grow/seed.c",
    "grow/water.c",
    "grow/soil.c",
]

[[targets]]
name = "libgrow"
type = "static"
sources = ["grow"]

[[targets]]
name = "libtomato"
type = "shared"
sources = ["tomatoes"]
link = "libgrow"
