# vim: et ts=4 sw=4
[project]
name = "libtomato"
version = "1"

[target.grow]
type = "archive"
headers = "grow.h"
sources = [
    "seed.c",
    "soil.c",
    "water.c",
]

[target.tomato]
type = ["dynamic", "archive"]
needs = "grow"
headers = "tomato.h"
sources = [
    "san_marzano.c",
    "beefmaster.c",
]

[target.pomodoro]
type = "binary"
path = "."
needs = ["grow", "tomato"]
sources = "pomodoro.c"
