# vim: et ts=4 sw=4
[project]
name = "libtomato"
version = "1"

[target.grow]
type = "static"
headers = "grow.h"
sources = [
    "seed.c",
    "soil.c",
    "water.c",
]

[target.tomato]
type = ["dynamic", "static"]
needs = "grow"
headers = "tomatoes.h"
sources = [
    "san_marzano.c",
    "beefmaster.c",
]
